# Generated by Django 5.1.5 on 2025-05-22 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserCredential',
        ),
    ]
